# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'LimeSurvey學習手冊'
copyright = '2017-2020, 依瑪貓, 2017-2018, 國立臺灣師範大學, 2020, 智新資通'
author = '依瑪貓, 智新資通'

# The full version, including alpha/beta/rc tags
release = '4.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_TW'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


##################
# Local settings #
##################
version = release
master_doc = 'index'
target_name = 'learning-limesurvey'

latex_elements = {
     'preamble': """
\\setCJKmainfont{AR PL UMing TW}
\\setCJKsansfont{AR PL UKai TW}
""",
}

latex_documents = [
    (master_doc, F'{target_name}.tex', project,
     author, 'manual'),
]
latex_appendices = ['apx-01-copy', 'apx-02-ab-testing']

man_pages = [
    (master_doc, target_name, project,
     [author], 1)
]

texinfo_documents = [
    (master_doc, target_name, project,
     author, 'Learning LimeSurvey', project,
     'Miscellaneous'),
]

epub_basename = target_name
